Repository salesforce/aws-allowlister, pull requests merged in 2021-04, with the labels that each got.

#70 Fix PyUp with GitHub actions workaround
  .github/workflows/python-dependency-updater.yml
Labels: automation

#73 Add version bump automation
  .github/workflows/bump-version.yml
  utils/bump-version.sh
Labels: automation, cla:missing

#75 Add schedule to update database
  .github/workflows/cron.yml
Labels: cla:signed

#77 migrate to config + loop, add DOD requirements
  .github/workflows/cron.yml
  utils/config.json
  utils/generate_new_scps.sh
Labels: cla:signed
