Repository salesforce/aws-allowlister, pull requests merged in 2021-02, with the labels that each got.

#50 `ssmmessages` and `ec2messages` are compliant when SSM is compliant (fixes #48)
  aws_allowlister/bin/version.py
  aws_allowlister/data/compliance.db
  aws_allowlister/data/compliance_statuses.csv
  aws_allowlister/data/compliance_statuses.xlsx
  aws_allowlister/data/hipaa-eligible-services-reference.html
  aws_allowlister/data/iso-certified.html
  aws_allowlister/data/overrides.yml
  aws_allowlister/data/services-in-scope.html
  aws_allowlister/database/build.py
  aws_allowlister/scrapers/tables/fedramp.py
  aws_allowlister/scrapers/tables/hipaa.py
  aws_allowlister/scrapers/tables/iso.py
  aws_allowlister/scrapers/tables/standard.py
  setup.cfg
  test/scrapers/test_override_fixes.py
  utils/update_data.py
Labels: bug

#53 Update README with support statuses
  README.md
Labels: documentation

#58 Add DOD CC SRG Support; Fix FedRAMP High bug
  README.md
  aws_allowlister/command/generate.py
  aws_allowlister/data/compliance.db
  aws_allowlister/data/compliance_statuses.csv
  aws_allowlister/data/compliance_statuses.xlsx
  aws_allowlister/database/build.py
  aws_allowlister/database/compliance_data.py
  aws_allowlister/database/database.py
  aws_allowlister/scrapers/tables/dodccsrg.py
  aws_allowlister/scrapers/tables/fedramp.py
  test/command/test_generate.py
  test/database/test_compliance_data.py
  test/scrapers/test_dodccsrg_il2_ew_matches.py
  test/scrapers/test_dodccsrg_il2_gc_matches.py
  test/scrapers/test_dodccsrg_il4_gc_matches.py
  test/scrapers/test_dodccsrg_il5_gc_matches.py
  test/scrapers/test_fedramp_high_matches.py
Labels: cla:signed

#59 Update README.md to reflect new command flags
  README.md
Labels: cla:signed

#60 [Snyk] Security upgrade pylint from 2.6.0 to 2.6.1
  requirements-dev.txt
Labels: cla:signed

#62 Adds Markdown table output support; bump to version 0.2.0
  README.md
  aws_allowlister/bin/version.py
  aws_allowlister/command/generate.py
  requirements.txt
  setup.py
  test/command/test_generate.py
Labels: enhancement
